### ISSUE TITLE
Question regarding copyright owner in source files

### ISSUE THREAD

**Issue by boskamp** [lukas-krecan/json2xml#11]
Thanks for this useful source code. I think about it including it in my own open source project. The question I have is related to the license headers in json2xml Java source code. My understanding of [HOW TO APPLY THE APACHE LICENSE TO YOUR WORK](http://apache.org/licenses/LICENSE-2.0.html#apply)  is that the source code header should list the **name(s)** of the copyright owner(s).

In json2xml source files, however, there is a more general statement "Copyright 2009-2013 **the original author or authors.**" That is, the name(s) of the copyright owners, such as your name - Lukáš Křečan - are not listed.

Assuming you're the copyright owner, could you please update the license headers to put your name in there, to avoid potential legal issues for downstream projects using your source code?

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. I do not understand all those legal issues, but I have checked Spring and they have the same header. For example https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/ApplicationContext.java,  I am hesitant to list the names since it would make merging other peoples work more complex. But since the project is dormant anyway, I will change the header
